
[[keyboard.bindings]]
action = "ResetFontSize"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Right"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Up"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Down"
mods = "Control"

[general]
live_config_reload = true
working_directory = "None"

[terminal]

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[cursor]
thickness = 0.15
unfocused_hollow = false

[cursor.style]
blinking = "Always"
shape = "Underline"

[env]
TERM = "alacritty"

[font]
size = 13

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"


[scrolling]
history = 100000
multiplier = 3

[terminal.shell]
program = "/home/esc2/.scripts/zsh-launcher"

[window]
opacity = 0.9

[keyboard]
